[build]
  publish = "build"  # or "dist", "public", etc., depending on your setup
  command = "npm run build"  # or the build command you use

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
